spring.application.name=notification-service

server.port=8084

# MongoDB
spring.data.mongodb.uri=mongodb://notification-mongodb:27017/library_notification
spring.data.mongodb.database=library_notification