spring.application.name=api-gateway
server.port=8085

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
management.endpoint.gateway.access=unrestricted
