spring.application.name=api-gateway
server.port=8085

# =========================
# BOOK SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[0].id=book-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/books/**


# =========================
# USER AUTH SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[1].id=user-auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**


# =========================
# USER SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/users,/users/**

# =========================
# BORROW SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[3].id=borrow-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/borrow/**


# =========================
# NOTIFICATION SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notifications/**

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=unrestricted