spring.application.name=api-gateway

server.port=8085

# Book Service

spring.cloud.gateway.server.webflux.routes[0].id=book-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/books/**


# User Service - Authentication

spring.cloud.gateway.server.webflux.routes[1].id=user-auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/auth/(?<segment>.*), /api/auth/${segment}

# User Service - User Management

spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/users/(?<segment>.*), /api/users/${segment}

# Borrow Service

spring.cloud.gateway.server.webflux.routes[3].id=borrow-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/borrow/**


# Notification Service

spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notifications/**