server.port=8081

# MongoDB Configuration (Update with your Atlas connection string if needed)
spring.data.mongodb.uri=mongodb://localhost:27017/library_user_db

# JWT Secret Key (Minimum 32 characters)
jwt.secret=YourSuperSecretKeyForLibraryManagementSystemService2026
jwt.expiration=86400000

# OpenAPI / Swagger UI Settings
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs