# Server Configuration
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/library_user_db
spring.data.mongodb.database=library_user_db

# JWT Configuration
jwt.secret=YourSuperSecretKeyForLibraryManagementSystemService2026
jwt.expiration=86400000

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Application
spring.application.name=user-service